### ISSUE TITLE
Error in cell 148

### ISSUE THREAD

**Issue by Shubhamai** [Pradeep1982/AMExpert19#1]
Hey, i like you repo very much. But there is a coding error in cell 148 on your jupyter notebook
#Drop id columns
==> data=data.drop(['id',axis=1]
data=data.drop(['date','start_date','end_date'],axis=1)

The line which is highlighted by arrow has a bracket problem. The solution for this is 
data=data.drop(['id'], axis=1)

**Comment by Pradeep1982** [comment]
Thanks shubham, I will  correct the same
